name: eslint-check

on: push

jobs:
  linter-tests:
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]

    steps:
      - uses: 'node20'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'node20'
        with: 
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: make install
      - name: run linter
        run: make lint
